//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metaseed.MetaShell.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Metaseed.MetaShell.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Application Startup Time is {0}ms.
        /// </summary>
        internal static string AppStartupTime {
            get {
                return ResourceManager.GetString("AppStartupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        internal static string Behavior {
            get {
                return ResourceManager.GetString("Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANDriverUsed.
        /// </summary>
        internal static string CANDriverUsed {
            get {
                return ResourceManager.GetString("CANDriverUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanvasHeight.
        /// </summary>
        internal static string CanvasHeight {
            get {
                return ResourceManager.GetString("CanvasHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas Height (&gt;=800).
        /// </summary>
        internal static string CanvasHeightDes {
            get {
                return ResourceManager.GetString("CanvasHeightDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanvasWidth.
        /// </summary>
        internal static string CanvasWidth {
            get {
                return ResourceManager.GetString("CanvasWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas Width (&gt;=1400).
        /// </summary>
        internal static string CanvasWidthDes {
            get {
                return ResourceManager.GetString("CanvasWidthDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        internal static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File Has Been Opened.(๑￫ܫ￩).
        /// </summary>
        internal static string FileOpenedMessage {
            get {
                return ResourceManager.GetString("FileOpenedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File Open Time is {0}ms.
        /// </summary>
        internal static string FileOpenTimeFormat {
            get {
                return ResourceManager.GetString("FileOpenTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File Has Been Saved. (・(ｪ)・).
        /// </summary>
        internal static string FileSavedMessage {
            get {
                return ResourceManager.GetString("FileSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File Saving Time is {0}ms.
        /// </summary>
        internal static string FileSaveTimeFormat {
            get {
                return ResourceManager.GetString("FileSaveTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {0} function blocks of this kind is alowed on the function designer canvas!.
        /// </summary>
        internal static string FunctionBlock_MaxNum {
            get {
                return ResourceManager.GetString("FunctionBlock_MaxNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstanceTitle.
        /// </summary>
        internal static string InstanceTitle {
            get {
                return ResourceManager.GetString("InstanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to distinguish different documents of the same type.
        /// </summary>
        internal static string InstanceTitleDescription {
            get {
                return ResourceManager.GetString("InstanceTitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Modify The Data While Display The Data.
        /// </summary>
        internal static string IsBidirectionalDescription {
            get {
                return ResourceManager.GetString("IsBidirectionalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;am Connecting The Network,  Please Waiting........ ≡￣﹏￣≡.
        /// </summary>
        internal static string NetWorkConnecting {
            get {
                return ResourceManager.GetString("NetWorkConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;am Try To Disconnect The Network, Please Waiting...(^_-)-☆.
        /// </summary>
        internal static string NetWorkDisConnecting {
            get {
                return ResourceManager.GetString("NetWorkDisConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open MetaStudio Package File.
        /// </summary>
        internal static string OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;am Openning The CANOpen Network Configuration File, Please Waiting.（*∩_∩*）..
        /// </summary>
        internal static string OpenMessage {
            get {
                return ResourceManager.GetString("OpenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save MetaStudio Package File.
        /// </summary>
        internal static string SaveFileDialogTitle {
            get {
                return ResourceManager.GetString("SaveFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;am Saving The File, Please Waiting...╮（￣▽￣）╭.
        /// </summary>
        internal static string SaveMessage {
            get {
                return ResourceManager.GetString("SaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        internal static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unopen.
        /// </summary>
        internal static string Unopen {
            get {
                return ResourceManager.GetString("Unopen", resourceCulture);
            }
        }
    }
}
