// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>Metaseed.MVVM.Commands</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>True</OrderXMLAttrib><EnableEncoding>True</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Metaseed.MVVM.Commands
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Xml;
    using System.Collections.Generic;


    public partial class RibbonButtonUIData : System.ComponentModel.INotifyPropertyChanged
    {

        private string iconURIField;

        private string shortCutKeysField;

        private string localizedHeaderField;

        private string sizeField;

        private RibbonButtonUIDataScreenTip screenTipField;

        private static System.Xml.Serialization.XmlSerializer serializer;

        /// <summary>
        /// RibbonButtonUIData class constructor
        /// </summary>
        public RibbonButtonUIData()
        {
            this.screenTipField = new RibbonButtonUIDataScreenTip();
        }

        public string IconURI
        {
            get
            {
                return this.iconURIField;
            }
            set
            {
                if ((this.iconURIField != null))
                {
                    if ((iconURIField.Equals(value) != true))
                    {
                        this.iconURIField = value;
                        this.OnPropertyChanged("IconURI");
                    }
                }
                else
                {
                    this.iconURIField = value;
                    this.OnPropertyChanged("IconURI");
                }
            }
        }

        public string ShortCutKeys
        {
            get
            {
                return this.shortCutKeysField;
            }
            set
            {
                if ((this.shortCutKeysField != null))
                {
                    if ((shortCutKeysField.Equals(value) != true))
                    {
                        this.shortCutKeysField = value;
                        this.OnPropertyChanged("ShortCutKeys");
                    }
                }
                else
                {
                    this.shortCutKeysField = value;
                    this.OnPropertyChanged("ShortCutKeys");
                }
            }
        }

        public string LocalizedHeader
        {
            get
            {
                return this.localizedHeaderField;
            }
            set
            {
                if ((this.localizedHeaderField != null))
                {
                    if ((localizedHeaderField.Equals(value) != true))
                    {
                        this.localizedHeaderField = value;
                        this.OnPropertyChanged("LocalizedHeader");
                    }
                }
                else
                {
                    this.localizedHeaderField = value;
                    this.OnPropertyChanged("LocalizedHeader");
                }
            }
        }

        public string Size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                if ((this.sizeField != null))
                {
                    if ((sizeField.Equals(value) != true))
                    {
                        this.sizeField = value;
                        this.OnPropertyChanged("Size");
                    }
                }
                else
                {
                    this.sizeField = value;
                    this.OnPropertyChanged("Size");
                }
            }
        }

        public RibbonButtonUIDataScreenTip ScreenTip
        {
            get
            {
                return this.screenTipField;
            }
            set
            {
                if ((this.screenTipField != null))
                {
                    if ((screenTipField.Equals(value) != true))
                    {
                        this.screenTipField = value;
                        this.OnPropertyChanged("ScreenTip");
                    }
                }
                else
                {
                    this.screenTipField = value;
                    this.OnPropertyChanged("ScreenTip");
                }
            }
        }

        private static System.Xml.Serialization.XmlSerializer Serializer
        {
            get
            {
                if ((serializer == null))
                {
                    serializer = new System.Xml.Serialization.XmlSerializer(typeof(RibbonButtonUIData));
                }
                return serializer;
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        #region Serialize/Deserialize
        /// <summary>
        /// Serializes current RibbonButtonUIData object into an XML document
        /// </summary>
        /// <returns>string XML value</returns>
        public virtual string Serialize(System.Text.Encoding encoding)
        {
            System.IO.StreamReader streamReader = null;
            System.IO.MemoryStream memoryStream = null;
            try
            {
                memoryStream = new System.IO.MemoryStream();
                System.Xml.XmlWriterSettings xmlWriterSettings = new System.Xml.XmlWriterSettings();
                xmlWriterSettings.Encoding = encoding;
                System.Xml.XmlWriter xmlWriter = XmlWriter.Create(memoryStream, xmlWriterSettings);
                Serializer.Serialize(xmlWriter, this);
                memoryStream.Seek(0, System.IO.SeekOrigin.Begin);
                streamReader = new System.IO.StreamReader(memoryStream);
                return streamReader.ReadToEnd();
            }
            finally
            {
                if ((streamReader != null))
                {
                    streamReader.Dispose();
                }
                if ((memoryStream != null))
                {
                    memoryStream.Dispose();
                }
            }
        }

        public virtual string Serialize()
        {
            return Serialize(Encoding.UTF8);
        }

        /// <summary>
        /// Deserializes workflow markup into an RibbonButtonUIData object
        /// </summary>
        /// <param name="xml">string workflow markup to deserialize</param>
        /// <param name="obj">Output RibbonButtonUIData object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        public static bool Deserialize(string xml, out RibbonButtonUIData obj, out System.Exception exception)
        {
            exception = null;
            obj = default(RibbonButtonUIData);
            try
            {
                obj = Deserialize(xml);
                return true;
            }
            catch (System.Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public static bool Deserialize(string xml, out RibbonButtonUIData obj)
        {
            System.Exception exception = null;
            return Deserialize(xml, out obj, out exception);
        }

        public static RibbonButtonUIData Deserialize(string xml)
        {
            System.IO.StringReader stringReader = null;
            try
            {
                stringReader = new System.IO.StringReader(xml);
                return ((RibbonButtonUIData)(Serializer.Deserialize(System.Xml.XmlReader.Create(stringReader))));
            }
            finally
            {
                if ((stringReader != null))
                {
                    stringReader.Dispose();
                }
            }
        }

        /// <summary>
        /// Serializes current RibbonButtonUIData object into file
        /// </summary>
        /// <param name="fileName">full path of outupt xml file</param>
        /// <param name="exception">output Exception value if failed</param>
        /// <returns>true if can serialize and save into file; otherwise, false</returns>
        public virtual bool SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
        {
            exception = null;
            try
            {
                SaveToFile(fileName, encoding);
                return true;
            }
            catch (System.Exception e)
            {
                exception = e;
                return false;
            }
        }

        public virtual bool SaveToFile(string fileName, out System.Exception exception)
        {
            return SaveToFile(fileName, Encoding.UTF8, out exception);
        }

        public virtual void SaveToFile(string fileName)
        {
            SaveToFile(fileName, Encoding.UTF8);
        }

        public virtual void SaveToFile(string fileName, System.Text.Encoding encoding)
        {
            System.IO.StreamWriter streamWriter = null;
            try
            {
                string xmlString = Serialize(encoding);
                streamWriter = new System.IO.StreamWriter(fileName, false, Encoding.UTF8);
                streamWriter.WriteLine(xmlString);
                streamWriter.Close();
            }
            finally
            {
                if ((streamWriter != null))
                {
                    streamWriter.Dispose();
                }
            }
        }

        /// <summary>
        /// Deserializes xml markup from file into an RibbonButtonUIData object
        /// </summary>
        /// <param name="fileName">string xml file to load and deserialize</param>
        /// <param name="obj">Output RibbonButtonUIData object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        public static bool LoadFromFile(string fileName, System.Text.Encoding encoding, out RibbonButtonUIData obj, out System.Exception exception)
        {
            exception = null;
            obj = default(RibbonButtonUIData);
            try
            {
                obj = LoadFromFile(fileName, encoding);
                return true;
            }
            catch (System.Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public static bool LoadFromFile(string fileName, out RibbonButtonUIData obj, out System.Exception exception)
        {
            return LoadFromFile(fileName, Encoding.UTF8, out obj, out exception);
        }

        public static bool LoadFromFile(string fileName, out RibbonButtonUIData obj)
        {
            System.Exception exception = null;
            return LoadFromFile(fileName, out obj, out exception);
        }

        public static RibbonButtonUIData LoadFromFile(string fileName)
        {
            return LoadFromFile(fileName, Encoding.UTF8);
        }

        public static RibbonButtonUIData LoadFromFile(string fileName, System.Text.Encoding encoding)
        {
            System.IO.FileStream file = null;
            System.IO.StreamReader sr = null;
            try
            {
                file = new System.IO.FileStream(fileName, FileMode.Open, FileAccess.Read);
                sr = new System.IO.StreamReader(file, encoding);
                string xmlString = sr.ReadToEnd();
                sr.Close();
                file.Close();
                return Deserialize(xmlString);
            }
            finally
            {
                if ((file != null))
                {
                    file.Dispose();
                }
                if ((sr != null))
                {
                    sr.Dispose();
                }
            }
        }
        #endregion
    }

    public partial class RibbonButtonUIDataScreenTip : System.ComponentModel.INotifyPropertyChanged
    {

        private string localizedTitleField;

        private string localizedTextField;

        private string localizedDisableReasonField;

        private string iconURIField;

        private static System.Xml.Serialization.XmlSerializer serializer;

        public string LocalizedTitle
        {
            get
            {
                return this.localizedTitleField;
            }
            set
            {
                if ((this.localizedTitleField != null))
                {
                    if ((localizedTitleField.Equals(value) != true))
                    {
                        this.localizedTitleField = value;
                        this.OnPropertyChanged("LocalizedTitle");
                    }
                }
                else
                {
                    this.localizedTitleField = value;
                    this.OnPropertyChanged("LocalizedTitle");
                }
            }
        }

        public string LocalizedText
        {
            get
            {
                return this.localizedTextField;
            }
            set
            {
                if ((this.localizedTextField != null))
                {
                    if ((localizedTextField.Equals(value) != true))
                    {
                        this.localizedTextField = value;
                        this.OnPropertyChanged("LocalizedText");
                    }
                }
                else
                {
                    this.localizedTextField = value;
                    this.OnPropertyChanged("LocalizedText");
                }
            }
        }

        public string LocalizedDisableReason
        {
            get
            {
                return this.localizedDisableReasonField;
            }
            set
            {
                if ((this.localizedDisableReasonField != null))
                {
                    if ((localizedDisableReasonField.Equals(value) != true))
                    {
                        this.localizedDisableReasonField = value;
                        this.OnPropertyChanged("LocalizedDisableReason");
                    }
                }
                else
                {
                    this.localizedDisableReasonField = value;
                    this.OnPropertyChanged("LocalizedDisableReason");
                }
            }
        }

        public string IconURI
        {
            get
            {
                return this.iconURIField;
            }
            set
            {
                if ((this.iconURIField != null))
                {
                    if ((iconURIField.Equals(value) != true))
                    {
                        this.iconURIField = value;
                        this.OnPropertyChanged("IconURI");
                    }
                }
                else
                {
                    this.iconURIField = value;
                    this.OnPropertyChanged("IconURI");
                }
            }
        }

        private static System.Xml.Serialization.XmlSerializer Serializer
        {
            get
            {
                if ((serializer == null))
                {
                    serializer = new System.Xml.Serialization.XmlSerializer(typeof(RibbonButtonUIDataScreenTip));
                }
                return serializer;
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        #region Serialize/Deserialize
        /// <summary>
        /// Serializes current RibbonButtonUIDataScreenTip object into an XML document
        /// </summary>
        /// <returns>string XML value</returns>
        public virtual string Serialize(System.Text.Encoding encoding)
        {
            System.IO.StreamReader streamReader = null;
            System.IO.MemoryStream memoryStream = null;
            try
            {
                memoryStream = new System.IO.MemoryStream();
                System.Xml.XmlWriterSettings xmlWriterSettings = new System.Xml.XmlWriterSettings();
                xmlWriterSettings.Encoding = encoding;
                System.Xml.XmlWriter xmlWriter = XmlWriter.Create(memoryStream, xmlWriterSettings);
                Serializer.Serialize(xmlWriter, this);
                memoryStream.Seek(0, System.IO.SeekOrigin.Begin);
                streamReader = new System.IO.StreamReader(memoryStream);
                return streamReader.ReadToEnd();
            }
            finally
            {
                if ((streamReader != null))
                {
                    streamReader.Dispose();
                }
                if ((memoryStream != null))
                {
                    memoryStream.Dispose();
                }
            }
        }

        public virtual string Serialize()
        {
            return Serialize(Encoding.UTF8);
        }

        /// <summary>
        /// Deserializes workflow markup into an RibbonButtonUIDataScreenTip object
        /// </summary>
        /// <param name="xml">string workflow markup to deserialize</param>
        /// <param name="obj">Output RibbonButtonUIDataScreenTip object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        public static bool Deserialize(string xml, out RibbonButtonUIDataScreenTip obj, out System.Exception exception)
        {
            exception = null;
            obj = default(RibbonButtonUIDataScreenTip);
            try
            {
                obj = Deserialize(xml);
                return true;
            }
            catch (System.Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public static bool Deserialize(string xml, out RibbonButtonUIDataScreenTip obj)
        {
            System.Exception exception = null;
            return Deserialize(xml, out obj, out exception);
        }

        public static RibbonButtonUIDataScreenTip Deserialize(string xml)
        {
            System.IO.StringReader stringReader = null;
            try
            {
                stringReader = new System.IO.StringReader(xml);
                return ((RibbonButtonUIDataScreenTip)(Serializer.Deserialize(System.Xml.XmlReader.Create(stringReader))));
            }
            finally
            {
                if ((stringReader != null))
                {
                    stringReader.Dispose();
                }
            }
        }

        /// <summary>
        /// Serializes current RibbonButtonUIDataScreenTip object into file
        /// </summary>
        /// <param name="fileName">full path of outupt xml file</param>
        /// <param name="exception">output Exception value if failed</param>
        /// <returns>true if can serialize and save into file; otherwise, false</returns>
        public virtual bool SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
        {
            exception = null;
            try
            {
                SaveToFile(fileName, encoding);
                return true;
            }
            catch (System.Exception e)
            {
                exception = e;
                return false;
            }
        }

        public virtual bool SaveToFile(string fileName, out System.Exception exception)
        {
            return SaveToFile(fileName, Encoding.UTF8, out exception);
        }

        public virtual void SaveToFile(string fileName)
        {
            SaveToFile(fileName, Encoding.UTF8);
        }

        public virtual void SaveToFile(string fileName, System.Text.Encoding encoding)
        {
            System.IO.StreamWriter streamWriter = null;
            try
            {
                string xmlString = Serialize(encoding);
                streamWriter = new System.IO.StreamWriter(fileName, false, Encoding.UTF8);
                streamWriter.WriteLine(xmlString);
                streamWriter.Close();
            }
            finally
            {
                if ((streamWriter != null))
                {
                    streamWriter.Dispose();
                }
            }
        }

        /// <summary>
        /// Deserializes xml markup from file into an RibbonButtonUIDataScreenTip object
        /// </summary>
        /// <param name="fileName">string xml file to load and deserialize</param>
        /// <param name="obj">Output RibbonButtonUIDataScreenTip object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        public static bool LoadFromFile(string fileName, System.Text.Encoding encoding, out RibbonButtonUIDataScreenTip obj, out System.Exception exception)
        {
            exception = null;
            obj = default(RibbonButtonUIDataScreenTip);
            try
            {
                obj = LoadFromFile(fileName, encoding);
                return true;
            }
            catch (System.Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public static bool LoadFromFile(string fileName, out RibbonButtonUIDataScreenTip obj, out System.Exception exception)
        {
            return LoadFromFile(fileName, Encoding.UTF8, out obj, out exception);
        }

        public static bool LoadFromFile(string fileName, out RibbonButtonUIDataScreenTip obj)
        {
            System.Exception exception = null;
            return LoadFromFile(fileName, out obj, out exception);
        }

        public static RibbonButtonUIDataScreenTip LoadFromFile(string fileName)
        {
            return LoadFromFile(fileName, Encoding.UTF8);
        }

        public static RibbonButtonUIDataScreenTip LoadFromFile(string fileName, System.Text.Encoding encoding)
        {
            System.IO.FileStream file = null;
            System.IO.StreamReader sr = null;
            try
            {
                file = new System.IO.FileStream(fileName, FileMode.Open, FileAccess.Read);
                sr = new System.IO.StreamReader(file, encoding);
                string xmlString = sr.ReadToEnd();
                sr.Close();
                file.Close();
                return Deserialize(xmlString);
            }
            finally
            {
                if ((file != null))
                {
                    file.Dispose();
                }
                if ((sr != null))
                {
                    sr.Dispose();
                }
            }
        }
        #endregion
    }
}
